### ISSUE TITLE
`horaedb-client` can't be found on PyPi

### ISSUE THREAD

**Issue by suyanhanx** [apache/horaedb-client-py#39]
It looks like you have finished renaming the project and updated the install command in readme. 
But I noticed that I can't find it on PyPi yet. 

Would you consider re-releasing it with the new name?

**Comment by chunshao90** [comment]
Recently we are releasing version 2.0.0, including releasing `horaedb-client` to PyPi. cc @tanruixiang

**Comment by jiacai2050** [comment]
https://pypi.org/project/horaedb-client/

I already pushed a RC version, will make a official release soon.
